language: c
matrix:
  include:
   - os: osx
     osx_image: xcode10
     compiler: clang
     env:
      - NUM_CPUS=$(sysctl -n hw.ncpu)
      - TOOLCHAIN="XCODE5"
     before_install:
      - brew install cctools nasm
      - ln -s /usr/local/opt/cctools/bin/mtoc /usr/local/bin/mtoc

   - os: linux
     dist: xenial
     compiler: clang
     env:
      - NUM_CPUS=$(nproc)
      - TOOLCHAIN="CLANG38"
     addons:
       apt:
         update: true
         sources:
          - sourceline: "ppa:git-core/ppa"
          - sourceline: "ppa:ubuntu-toolchain-r/test"
          - sourceline: "ppa:jonathonf/nasm"
          - sourceline: "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main"
            key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
         packages:
          - clang-7
          - git-svn
          - llvm-7
          - llvm-7-dev
          - nasm
     before_install:
       - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-7 1000
                                  --slave /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-7

   - os: linux
     dist: xenial
     compiler: gcc
     env:
      - NUM_CPUS=$(nproc)
      - TOOLCHAIN="GCC5"
     addons:
       apt:
         update: true
         sources:
          - sourceline: "ppa:git-core/ppa"
          - sourceline: "ppa:ubuntu-toolchain-r/test"
          - sourceline: "ppa:jonathonf/nasm"
         packages:
          - gcc-8
          - git-svn
          - nasm
     before_install:
       - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 1000
                                  --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-8

install:
 - git clone https://github.com/tianocore/edk2 ../edk2 --depth 1
 - make -C ../edk2/BaseTools -j $NUM_CPUS -s

before_script:
 - cd ../edk2
 - source edksetup.sh
 - export PACKAGES_PATH="$(pwd)/.."
 - cd $TRAVIS_BUILD_DIR
 - ./gen-version.sh $TOOLCHAIN

script:
 - build -p Clover/Clover.dsc -a IA32 -b RELEASE -t $TOOLCHAIN -n $NUM_CPUS -s -D NO_CLOVER_SHELL -D NO_GRUB_DRIVERS
 - build -p Clover/Clover.dsc -a X64 -b RELEASE -t $TOOLCHAIN -n $NUM_CPUS -s -D NO_CLOVER_SHELL -D NO_GRUB_DRIVERS
